import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
      flex: 1,
    },
    timKiem: {
      borderRadius: 8,
      paddingLeft: 20,
      backgroundColor: 'white',
      color: 'black',
      paddingRight: 55,
    },
    trangTri: {
      width: '100%',
      position: 'absolute',
      top: 0,
    },
    box1: {
      backgroundColor: 'white',
      height: '85%',
      marginHorizontal: 30,
      borderRadius: 15,
      elevation: 2,
      alignItems: 'center',
    },
    title: {
      color: 'black',
      fontSize: 16,
      fontWeight: 'bold',
      marginVertical: 15,
    },
    modalLuaChon: {
      width: 380,
      height: 402,
      backgroundColor: '#F0F0F0',
      justifyContent: 'center',
      alignItems: 'center',
      alignSelf: 'center',
      marginTop: 'auto',
      marginBottom: 'auto',
      borderRadius: 20,
    },
    image: {
      width: 204,
      height: 200,
    },
    text: {
      fontSize: 22,
      color: 'black',
      fontWeight: '700',
      marginTop: 10,
    },
    button: {
      backgroundColor: 'black',
      justifyContent: 'center',
      alignItems: 'center',
      width: '80%',
      borderRadius: 10,
      marginVertical: 10,
    },
    text1: {
      color: 'white',
      fontSize: 16,
      paddingVertical: 12,
    },
    back: {
      width: 25,
      height: 25,
      borderRadius: 7,
      backgroundColor: 'white',
      justifyContent: 'center',
      alignItems: 'center',
      position: 'absolute',
      top: 10,
      left: 20,
    },
    btnThem: {
      width: 50,
      height: 50,
      backgroundColor: '#FBD141',
      borderRadius: 50,
      justifyContent: 'center',
      alignItems: 'center',
      margin: 10,
    },
    modalChiTiet: {
      backgroundColor: 'white',
      marginHorizontal: 30,
      borderRadius: 15,
      elevation: 2,
      alignItems: 'center',
      marginTop: 'auto',
      marginBottom: 'auto',
      paddingVertical: 20,
      height: '92%',
    },
    text2: {
      margin: 10,
      fontSize: 20,
      color: 'black',
      fontWeight: 'bold',
    },
    box2: {
      width: '90%',
      margin: 10,
      borderRadius: 20,
      height: '70%',
      backgroundColor: '#F7F8F9',
    },
    text3: {
      marginLeft: 12,
      marginTop: 14,
      color: 'black',
      fontSize: 16,
      fontWeight: '600',
    },
    btnQuayLai: {
      backgroundColor: 'black',
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 10,
      margin: 10,
    },
    backH: {
      width: 30,
      height: 30,
      borderRadius: 10,
      backgroundColor: 'white',
      justifyContent: 'center',
      alignItems: 'center',
      position: 'absolute',
      top: 10,
      left: 20,
      borderWidth: 1,
    },
    edittext: {
      width: '90%',
      borderWidth: 1,
      backgroundColor: '#F7F8F9',
      borderRadius: 10,
      borderColor: '#E8ECF4',
      marginTop: 15,
      paddingLeft: 15,
    },
    dropdown: {
      width: '90%',
      borderWidth: 1,
      backgroundColor: '#F7F8F9',
      borderRadius: 10,
      borderColor: '#E8ECF4',
      marginTop: 15,
    },
    viewThem: {
      width: '100%',
    },
    viewInput: {
      width: '100%',
      alignItems: 'center',
    },
    errorText: {
      marginLeft: '7%',
      marginTop: 5,
      color: 'red',
    },
    btnXacNhan: {
      width: '45%',
      backgroundColor: 'black',
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 10,
      margin: 10,
    },
    modalThanhCong: {
      width: 320,
      height: 60,
      backgroundColor: '#E8E8E8',
      justifyContent: 'center',
      alignItems: 'center',
      alignSelf: 'center',
      marginTop: 'auto',
      marginBottom: 40,
      borderRadius: 10,
      borderWidth: 1,
    },
    tenNhanVien: {
      color: 'black',
      marginLeft: 20,
      marginVertical: 10,
      fontSize: 16,
    },
    searchTen: {
      position: 'absolute',
      top: 10,
      right: 10,
    },
    employeeImage: {
        width: 150,
        height: 150,
        marginTop: 20, 
        resizeMode: 'cover',
        borderColor: 'black',
        borderWidth: 1,
        borderRadius: 10
    }
  });
  